<?php

namespace app\modules\book\models;

use Yii;

/**
 * This is the model class for table "book_subscription".
 *
 * @property int $id
 * @property int $book_id
 * @property int $phone
 *
 * @property Book $book
 * @property Book $actualBook
 */
class BookSubscription extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'book_subscription';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['book_id', 'phone'], 'required'],
            [['book_id'], 'integer'],
            [['phone'], 'match', 'pattern' => '/^\+7\s\([0-9]{3}\)\s[0-9]{3}\-[0-9]{2}\-[0-9]{2}$/',],
            [['book_id'], 'exist', 'skipOnError' => true, 'targetClass' => Book::class, 'targetAttribute' => ['book_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'book_id' => 'Book ID',
            'phone' => 'Phone',
        ];
    }

    /**
     * Gets query for [[Book]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getBook()
    {
        return $this->hasOne(Book::class, ['id' => 'book_id']);
    }

    /**
     * Gets query for [[Book]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getActualBook()
    {
        return $this->hasOne(Book::class, ['id' => 'book_id'])->where(['books.is_deleted' => false]);
    }

    public function beforeSave($insert)
    {
        $this->phone = preg_replace('/[^0-9]/', '', $this->phone);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
